[theme]
base = "dark"
primaryColor = "rgba(255, 255, 255, 1)"
backgroundColor = "rgba(30, 30, 30, 1)"
secondaryBackgroundColor = "rgba(45, 45, 45, 0.38)"
textColor = "rgba(255, 255, 255, 1)"
font = "sans serif"